### PR TITLE
A few misc tidy-ups

### PR DESCRIPTION
**Pull request by alexdewar**
While working on a new template using cookiecutter, I found a few small issues with the current template:

* Missing return-type annotation in test
* Remove unnecessary `__init__.py` file in `tests` folder
* Use `importlib` to find the package version in a more robust way
* Drop `ruff` from dev dependencies (the `pre-commit` hook and VS Code extension both use bundled versions)
* Use consistent case for project name

### CODE REVIEW

**Comment by AdrianDAlessandro** [comment]
I disagree with needing a return type annotation in tests since they all, but design, return `None`. This is why there is the mypy override in the `pyproject.toml`. Also, I believe we need to the `__init__.py` in the tests file for that override to work properly, I just removed it in an existing repo and had a bunch of mypy errors when I ran `pytest`.

The `importlib` idea is great! Does that also work for pip-tools?

**Review by AdrianDAlessandro — APPROVED** [review]
Works for me

**Comment by alexdewar** [comment]
> The `importlib` thing _should_ work with `pip-tools` or anything else really as long as the project is actually installed as part of the build process (as I think it is).

Turns out it doesn't work with `pip-tools` :upside_down_face:. Weird that `pip` doesn't install the current project, but seemingly it doesn't.

**Comment by alexdewar** [comment]
@cc-a Ahh ok. I'll put it back then. Also, I've noticed `mypy` isn't in the dev dependencies, although we use it for linting. Do you think we should add that too?

**Comment by AdrianDAlessandro** [comment]
> Turns out it doesn't work with `pip-tools` 🙃. Weird that `pip` doesn't install the current project, but seemingly it doesn't.

It does work, but you have to do `pip install -e ".[dev]"` 

> @cc-a Ahh ok. I'll put it back then. Also, I've noticed mypy isn't in the dev dependencies, although we use it for linting. Do you think we should add that too?

It might be installed along with `pytest-mypy`?

**Comment by alexdewar** [comment]
Aha. Right on both counts @AdrianDAlessandro

**Pull request merged**
