### PR TITLE
Mandate docstrings for all public modules, methods etc.

### PR DESCRIPTION
**Pull request by alexdewar**
Hi both,

I thought this might merit discussion and I thought the easiest way to do that was just to open a PR.

After just having gone through the pain of going through the iPANACEA code base and adding docstrings everywhere, I'm wondering whether for new projects we should just mandate them? Obviously people can opt out by changing the settings back again, but I feel like it's probably sensible to require docstrings from the get-go. It isn't like the whole mypy thing, where people may or may not want to enforce types; regardless of what kind of project we're doing, I think it makes sense to have docstrings.

What do you think?

### CODE REVIEW

**Comment by alexdewar** [comment]
Heh, the CI for this branch is failing for obvious reasons, but I'm happy to fix it up if this is something we'd like to do.

**Review by dalonsoa — CHANGES_REQUESTED** [review]
Rather than removing that code altogether, I'd leave the line commented and change the explanation to something like "Uncomment to disable enforcing docstrings... bla, bla, bla", so it is easier for people to enable/disable that functionality.

**Review by cc-a — CHANGES_REQUESTED** [review]
I agree that mandating is a better default position and think Diego's proposal is a good idea. Whilst we're changing this could we also swap to using `extend-ignore`? Using `ignore` can cause issues with Black - see https://github.com/ImperialCollegeLondon/iPANACEA/commit/5e9f5cfa87331cca208631b46b4d061ae75e9a22

**Comment by alexdewar** [comment]
Good suggestions both!

**Comment by alexdewar** [comment]
I've had another go.

I also disabled log capture for ``pytest`` because it was producing unnecessarily verbose output for ``flake8`` failures, e.g.:

```
_________________________________________ FLAKE8-check _________________________________________
/home/alex/code/poetry_template_2/tests/test_myproject.py:1:1: D100 Missing docstring in public module

-------------------------------------- Captured log call ---------------------------------------
WARNING  flake8.options.manager:manager.py:217 option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future

---------- coverage: platform linux, python 3.9.13-final-0 -----------
Coverage HTML written to dir htmlcov/coverage
```

**Review by dalonsoa — APPROVED** [review]
Looks good!

**Review by cc-a — COMMENTED** [review]
Docstring change looks great.

I'd prefer something more targeted on the logging front. Are we sure this hasn't been resolved by newer versions of flake8? We're a whole major version behind at the moment. Otherwise I think the `conftest.py` suggested at https://github.com/eisensheng/pytest-catchlog/issues/59 would be acceptable.

**Comment by alexdewar** [comment]
That's a good suggestion; it's much cleaner that way.

**Review by cc-a — APPROVED** [review]

**Pull request merged**
